# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\dudcj\OneDrive\Desktop\AI_Study\FastCampus\Python\naver_soldout_check\scripts\alarm_setting.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AlarmSettingForm(object):
    def setupUi(self, AlarmSettingForm):
        AlarmSettingForm.setObjectName("AlarmSettingForm")
        AlarmSettingForm.resize(311, 155)
        self.lineEdit_hours = QtWidgets.QLineEdit(AlarmSettingForm)
        self.lineEdit_hours.setGeometry(QtCore.QRect(60, 40, 41, 21))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        self.lineEdit_hours.setFont(font)
        self.lineEdit_hours.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_hours.setObjectName("lineEdit_hours")
        self.btn_apply = QtWidgets.QPushButton(AlarmSettingForm)
        self.btn_apply.setGeometry(QtCore.QRect(70, 100, 81, 29))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(9)
        self.btn_apply.setFont(font)
        self.btn_apply.setObjectName("btn_apply")
        self.label = QtWidgets.QLabel(AlarmSettingForm)
        self.label.setGeometry(QtCore.QRect(110, 40, 151, 21))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_cancle = QtWidgets.QPushButton(AlarmSettingForm)
        self.btn_cancle.setGeometry(QtCore.QRect(160, 100, 81, 29))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(9)
        self.btn_cancle.setFont(font)
        self.btn_cancle.setObjectName("btn_cancle")

        self.retranslateUi(AlarmSettingForm)
        QtCore.QMetaObject.connectSlotsByName(AlarmSettingForm)

    def retranslateUi(self, AlarmSettingForm):
        _translate = QtCore.QCoreApplication.translate
        AlarmSettingForm.setWindowTitle(_translate("AlarmSettingForm", "Form"))
        self.lineEdit_hours.setText(_translate("AlarmSettingForm", "1"))
        self.btn_apply.setText(_translate("AlarmSettingForm", "적용"))
        self.label.setText(_translate("AlarmSettingForm", "시간 마다 알림 받기"))
        self.btn_cancle.setText(_translate("AlarmSettingForm", "취소"))
