# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\dudcj\OneDrive\Desktop\AI_Study\FastCampus\Python\myGit\naver-store-restock-alarm\ui\input_url.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(572, 166)
        self.text_input_url = QtWidgets.QPlainTextEdit(Dialog)
        self.text_input_url.setGeometry(QtCore.QRect(80, 30, 471, 81))
        self.text_input_url.setPlainText("")
        self.text_input_url.setObjectName("text_input_url")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 30, 41, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_confirm = QtWidgets.QPushButton(Dialog)
        self.btn_confirm.setGeometry(QtCore.QRect(360, 120, 90, 30))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(9)
        self.btn_confirm.setFont(font)
        self.btn_confirm.setObjectName("btn_confirm")
        self.btn_cancle = QtWidgets.QPushButton(Dialog)
        self.btn_cancle.setGeometry(QtCore.QRect(460, 120, 90, 30))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(9)
        self.btn_cancle.setFont(font)
        self.btn_cancle.setObjectName("btn_cancle")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "URL :"))
        self.btn_confirm.setText(_translate("Dialog", "확인"))
        self.btn_cancle.setText(_translate("Dialog", "취소"))
