# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\dudcj\OneDrive\Desktop\AI_Study\FastCampus\Python\myGit\naver-store-restock-alarm\ui\soldout_check.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWIndow(object):
    def setupUi(self, MainWIndow):
        MainWIndow.setObjectName("MainWIndow")
        MainWIndow.resize(918, 520)
        self.centralwidget = QtWidgets.QWidget(MainWIndow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_alarm_setting = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(9)
        self.btn_alarm_setting.setFont(font)
        self.btn_alarm_setting.setObjectName("btn_alarm_setting")
        self.gridLayout.addWidget(self.btn_alarm_setting, 0, 3, 1, 1)
        self.btn_insert = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(9)
        self.btn_insert.setFont(font)
        self.btn_insert.setObjectName("btn_insert")
        self.gridLayout.addWidget(self.btn_insert, 0, 0, 1, 1)
        self.btn_get_alarm = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(9)
        self.btn_get_alarm.setFont(font)
        self.btn_get_alarm.setObjectName("btn_get_alarm")
        self.gridLayout.addWidget(self.btn_get_alarm, 0, 2, 1, 1)
        self.btn_remove = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(9)
        self.btn_remove.setFont(font)
        self.btn_remove.setObjectName("btn_remove")
        self.gridLayout.addWidget(self.btn_remove, 0, 1, 1, 1)
        self.btn_debug = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(9)
        self.btn_debug.setFont(font)
        self.btn_debug.setObjectName("btn_debug")
        self.gridLayout.addWidget(self.btn_debug, 0, 4, 1, 1)
        self.table_product = QtWidgets.QTableWidget(self.centralwidget)
        self.table_product.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_product.sizePolicy().hasHeightForWidth())
        self.table_product.setSizePolicy(sizePolicy)
        self.table_product.setObjectName("table_product")
        self.table_product.setColumnCount(0)
        self.table_product.setRowCount(0)
        self.table_product.horizontalHeader().setCascadingSectionResizes(False)
        self.table_product.horizontalHeader().setDefaultSectionSize(125)
        self.table_product.horizontalHeader().setStretchLastSection(True)
        self.table_product.verticalHeader().setCascadingSectionResizes(False)
        self.table_product.verticalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.table_product, 1, 0, 1, 5)
        MainWIndow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWIndow)
        QtCore.QMetaObject.connectSlotsByName(MainWIndow)

    def retranslateUi(self, MainWIndow):
        _translate = QtCore.QCoreApplication.translate
        MainWIndow.setWindowTitle(_translate("MainWIndow", "Naver Soldout Check"))
        self.btn_alarm_setting.setText(_translate("MainWIndow", "알림 설정"))
        self.btn_insert.setText(_translate("MainWIndow", "추가하기"))
        self.btn_get_alarm.setText(_translate("MainWIndow", "알림 받기"))
        self.btn_remove.setText(_translate("MainWIndow", "삭제하기"))
        self.btn_debug.setText(_translate("MainWIndow", "디버그"))
